INSERT INTO  ingredients (Ing_Nom, Ing_Categorie) VALUES
('abricot (fruit)','fruit'),
('abricot (jus)','jus'),
('abricot (liqueur)','liqueur'),
('abricot (sirop)','sirop'),
('absinthe','alcool'),
('amande (fruit)','fruit'),
('amande (jus)','jus'),
('amande (liqueur)','liqueur'),
('amande (sirop)','sirop'),
('Amaretto','liqueur'),
('ananas (fruit)','fruit'),
('ananas (jus)','jus'),
('ananas (liqueur)','liqueur'),
('ananas (sirop)','sirop'),
('Angostura bitters','alcool'),
('anis �toil�','�pice/fleur/condiments'),
('baies de geni�vre','�pice/fleur/condiments'),
('banane (fruit)','fruit'),
('banane (jus)','jus'),
('banane (liqueur)','liqueur'),
('banane (sirop)','sirop'),
('basilic (sirop)','sirop'),
('basilic','�pice/fleur/condiments'),
('biere','alcool'),
('Bourbon ','alcool'),
('brandy','alcool'),
('camomille','�pice/fleur/condiments'),
('canelle','�pice/fleur/condiments'),
('caramel sal�','sirop'),
('cardamome','�pice/fleur/condiments'),
('cassis (fruit)','fruit'),
('cassis (jus)','jus'),
('cassis (liqueur)','liqueur'),
('cassis (sirop)','sirop'),
('cerise (fruit)','fruit'),
('cerise (jus)','jus'),
('cerise (liqueur)','liqueur'),
('cerise (sirop)','sirop'),
('champagne','alcool'),
('chocolat noir','�pice/fleur/condiments'),
('citron  (fruit)','fruit'),
('citron  (jus)','jus'),
('citron  (liqueur)','liqueur'),
('citron  (sirop)','sirop'),
('citron vert (fruit)','fruit'),
('citron vert (jus)','jus'),
('citron vert (liqueur)','liqueur'),
('citron vert (sirop)','sirop'),
('coco (creme)','creme'),
('coco (fruit)','fruit'),
('coco (jus)','jus'),
('coco (lait)','lait'),
('coco (liqueur)','liqueur'),
('coco (sirop)','sirop'),
('Cognac ','alcool'),
('Cointreau - Triple sec ','alcool'),
('cola','soda'),
('cramberry (fruit)','fruit'),
('cramberry (jus)','jus'),
('cramberry (liqueur)','liqueur'),
('cramberry (sirop)','sirop'),
('creme de cacao','liqueur'),
('creme de whisky ','alcool'),
('Drambuie','liqueur'),
('eau gazeuse','eau'),
('eau min�rale','eau'),
('fleur de jasmin','�pice/fleur/condiments'),
('fleur de sel','�pice/fleur/condiments'),
('fleur de sureaux (sirop)','sirop'),
('fleur de sureaux (liqueur)','liqueur'),
('fleur de violette','�pice/fleur/condiments'),
('fleur d''hibiscus','�pice/fleur/condiments'),
('fraise (fruit)','fruit'),
('fraise (jus)','jus'),
('fraise (liqueur)','liqueur'),
('fraise (sirop)','sirop'),
('fraise des bois (fruit)','fruit'),
('fraise des bois (jus)','jus'),
('fraise des bois (liqueur)','liqueur'),
('fraise des bois (sirop)','sirop'),
('framboise (fruit)','fruit'),
('framboise (jus)','jus'),
('framboise (liqueur)','liqueur'),
('framboise (sirop)','sirop'),
('fruits de la passion (fruit)','fruit'),
('fruits de la passion (jus)','jus'),
('fruits de la passion (liqueur)','liqueur'),
('fruits de la passion (sirop)','sirop'),
('Galliano (liqueur)','liqueur'),
('Gin ','alcool'),
('gingembre (fruit)','fruit'),
('gingembre (jus)','jus'),
('gingembre (liqueur)','liqueur'),
('gingembre (sirop)','sirop'),
('gingembre�','�pice/fleur/condiments'),
('ginger ale ','eau'),
('goyave (fruit)','fruit'),
('goyave (jus)','jus'),
('goyave (liqueur)','liqueur'),
('goyave (sirop)','sirop'),
('grappa','alcool'),
('jasmin','sirop'),
('kiwi (fruit)','fruit'),
('kiwi (jus)','jus'),
('kiwi (liqueur)','liqueur'),
('kiwi (sirop)','sirop'),
('laurier','�pice/fleur/condiments'),
('limonade','eau'),
('litchi (fruit)','fruit'),
('litchi (jus)','jus'),
('litchi (liqueur)','liqueur'),
('litchi (sirop)','sirop'),
('madarine (fruit)','fruit'),
('madarine (jus)','jus'),
('madarine (liqueur)','liqueur'),
('madarine (sirop)','sirop'),
('malibu (fruit)','fruit'),
('malibu (jus)','jus'),
('malibu (liqueur)','liqueur'),
('malibu (sirop)','sirop'),
('mandarine (fruit)','fruit'),
('mandarine (jus)','jus'),
('mandarine (liqueur)','liqueur'),
('mandarine (sirop)','sirop'),
('mangue (fruit)','fruit'),
('mangue (jus)','jus'),
('mangue (liqueur)','liqueur'),
('mangue (sirop)','sirop'),
('melon (fruit)','fruit'),
('melon (jus)','jus'),
('melon (liqueur)','liqueur'),
('melon (sirop)','sirop'),
('menthe','fruit'),
('Mezcal','alcool'),
('myrtille (fruit)','fruit'),
('myrtille (jus)','jus'),
('myrtille (liqueur)','liqueur'),
('myrtille (sirop)','sirop'),
('noix de muscade','�pice/fleur/condiments'),
('orange (fruit)','fruit'),
('orange (jus)','jus'),
('orange (liqueur)','liqueur'),
('orange (sirop)','sirop'),
('orgeat (sirop)','sirop'),
('pamplemeousse (fruit)','fruit'),
('pamplemeousse (jus)','jus'),
('pamplemeousse (liqueur)','liqueur'),
('pamplemeousse (sirop)','sirop'),
('passoa (fruit)','fruit'),
('passoa (jus)','jus'),
('passoa (liqueur)','liqueur'),
('passoa (sirop)','sirop'),
('peche (fruit)','fruit'),
('peche (jus)','jus'),
('peche (liqueur)','liqueur'),
('peche (sirop)','sirop'),
('peche de vigne (fruit)','fruit'),
('peche de vigne (jus)','jus'),
('peche de vigne (liqueur)','liqueur'),
('peche de vigne (sirop)','sirop'),
('piment','�pice/fleur/condiments'),
('piment de cayenne','�pice/fleur/condiments'),
('pisang ambon (fruit)','fruit'),
('pisang ambon (jus)','jus'),
('pisang ambon (liqueur)','liqueur'),
('pisang ambon (sirop)','sirop'),
('Pisco','alcool'),
('pistache (sirop)','sirop'),
('poire (fruit)','fruit'),
('poire (jus)','jus'),
('poire (liqueur)','liqueur'),
('poire (sirop)','sirop'),
('poivre blanc','�pice/fleur/condiments'),
('poivre noire','�pice/fleur/condiments'),
('poivron','�pice/fleur/condiments'),
('pomme (fruit)','fruit'),
('pomme (jus)','jus'),
('pomme (liqueur)','liqueur'),
('pomme (sirop)','sirop'),
('Porto','alcool'),
('Rhum','alcool'),
('sambucca','alcool'),
('sel','�pice/fleur/condiments'),
('Southern Comfort','liqueur'),
('speculos','sirop'),
('sucre','�pice/fleur/condiments'),
('Tequila ','alcool'),
('tonic','eau'),
('vanille','�pice/fleur/condiments'),
('Vermouth dry','alcool'),
('Vermouth rouge','alcool'),
('Vermouth blanc','alcool'),
('vin','alcool'),
('Vodka ','alcool'),
('whisky ','alcool'),
('yuzu','sirop')
